### ISSUE TITLE
Issue with your YouTube channel

### ISSUE THREAD

**Issue by curious08** [eddydn/XamarinChatApp#1]
Sorry to raise request here
I was following your Android tutorials and today suddenly it is showing account got suspended.

Please reactivate or recreate another channel and upload videos.

Your videos are the best one that I have encountered on YouTube.
Please reupload....

Thanks

**Comment by eddydn** [comment]
Dear friend

I have sent request to YouTube and we can waiting...

On Dec 29, 2016 00:39, "Sumesh Gupta" <notifications@github.com> wrote:

Sorry to raise request here
I was following your Android tutorials and today suddenly it is showing
account got suspended.

Please reactivate or recreate another channel and upload videos.

Your videos are the best one that I have encountered on YouTube.
Please reupload....

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/eddydn/XamarinChatApp/issues/1>, or mute the thread

**Comment by curious08** [comment]
Thanks for update

**Comment by eddydn** [comment]
So can you help me , request Google about my Channel with me ?

here link my channel : http://www.youtube.com/eddydn71

2016-12-29 6:53 GMT+07:00 Sumesh Gupta <notifications@github.com>:

**Comment by curious08** [comment]
Yeah sure I will send a mail to Google
Actually I am a database developer and working on sql, plsql (oracle based technologies) and wanna learn Android and found your tutorial very helpful.

Is there other way I can support or raise request to google?
Thanks

**Comment by eddydn** [comment]
Dear

You can make email about my channel

https://www.youtube.com/eddydn71

And send it to three email below here :
account-appeal@youtube.com
accounts-support@google.com,
yt-partner-support@google.com

2016-12-29 8:28 GMT+07:00 Sumesh Gupta <notifications@github.com>:

**Comment by curious08** [comment]
ok doing....

**Comment by curious08** [comment]
![youtube block](https://cloud.githubusercontent.com/assets/7764122/21535190/9f47fdd2-cd97-11e6-964b-98d3d6609d8c.PNG)

**Comment by eddydn** [comment]
Dear

Thank you ! You're welcome :)

2016-12-29 8:53 GMT+07:00 Sumesh Gupta <notifications@github.com>:

**Comment by curious08** [comment]
Welcome Friend 👍

**Comment by curious08** [comment]
Any update ??

Did you save your videos in cloud. If yes please share the link.

**Comment by eddydn** [comment]
Dear.  Can you wwaiting for 24 hours later...  i have wait for google reply


On Dec 29, 2016 19:05, "Sumesh Gupta" <notifications@github.com> wrote:

Any update ??

Did you save your videos in cloud. If yes please share the link.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/eddydn/XamarinChatApp/issues/1#issuecomment-269621150>,
or mute the thread

**Comment by smartshehbaaz** [comment]
mr eddy can you please create another youtube account and upload videos again
or else please share those videos on google drive
it will be very helpful
thank you

**Comment by eddydn** [comment]
Dear !

I've try all my best to contact with Youtube for restore my channel

It can take by long time (2~4 days) because Youtube need time to review my
channel

You need other tutorial ? just tell me ?

2016-12-30 16:45 GMT+07:00 smartshehbaaz <notifications@github.com>:

**Comment by smartshehbaaz** [comment]
actually i wanted see your xamarin android chat app tutorial 
after learning and implementing this

in addition i want to add a location pointing feature on that app for all the users who chat and use that app

please help

**Comment by curious08** [comment]
I need your android tutorial please share the link :)

**Comment by eddydn** [comment]
Now i don't have link of my tutorial  , you can waiting until next week
i'll create new channel

2016-12-30 17:08 GMT+07:00 Sumesh Gupta <notifications@github.com>:

**Comment by smartshehbaaz** [comment]
i am trying to run your project(xamarin chat app) on visual studio 
it is continuously in build only  
it is not showing the output

help me with solution

and also pls see my above question of map pointing

**Comment by eddydn** [comment]
Try to change url of Firebase

2016-12-30 17:48 GMT+07:00 smartshehbaaz <notifications@github.com>:

**Comment by curious08** [comment]
Eddydn do you have all your videos with you or you have lost all, I mean locally in your hard drive?

Wats your name?

**Comment by eddydn** [comment]
I'm try to restore all my videos

2016-12-30 17:59 GMT+07:00 Sumesh Gupta <notifications@github.com>:

**Comment by curious08** [comment]
Mr Eddy
I got the Android tutorial link and got to know why YouTube terminated your account.
Course link
https://www.udemy.com/complete-android-developer-course/
Thanks for your time :P

**Comment by eddydn** [comment]
Nope ! Most of all tutorial come from me :(

**Comment by eddydn** [comment]
My Channel disabled because Youtube scan spam channel and disable my email
:( , i've restored my email but YT Channel need contact more

2016-12-31 7:06 GMT+07:00 eddydn <eddydn@gmail.com>:

> Nope ! Most of all tutorial come from me :(
>

**Comment by curious08** [comment]
Congrats you got your channel back

Enjoy n happy new year :D

**Comment by eddydn** [comment]
Yeahhhhhh !!

Thank you ! Very thank you ! I've publish new new and more and more
tutorial about programing for you and community

2017-01-01 13:49 GMT+07:00 Sumesh Gupta <notifications@github.com>:
